name: Build Proxywoman

on:
  push:
#    branches: [ master ]
#  pull_request:
#    branches: [ master ]

jobs:

  build-linux:
    name: Linux Build
    runs-on: ubuntu-latest
    steps:
    - name: Install Dependencies
      run: sudo apt install gcc libgtk-3-dev libappindicator3-dev libwebkit2gtk-4.0-dev
    -
      name: Checkout
      uses: actions/checkout@v2
    -
      name: Unshallow
      run: git fetch --prune --unshallow
    -
      name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.14
    -
       name: Run Builds
       run: |
         rm -rf ./out
         ./build.sh linux server
         # ./build.sh linux desktop - Linux desktop build is not currently supported.
    - name: Upload Build Artifact
      uses: actions/upload-artifact@v2
      with:
        # Artifact name
        # name: # optional
        path: ./out/**/*
  
  build-darwin:
    name: Darwin Build
    runs-on: macos-latest
    steps:
    -
      name: Checkout
      uses: actions/checkout@v2
    -
      name: Unshallow
      run: git fetch --prune --unshallow
    -
      name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.14
    -
       name: Run Builds
       run: |
         rm -rf ./out
         ./build.sh darwin server
         ./build.sh darwin desktop
    - name: Upload Build Artifact
      uses: actions/upload-artifact@v2
      with:
        # Artifact name
        # name: # optional
        path: ./out/**/*
  
  build-windows:
    name: Windows Build
    runs-on: ubuntu-latest
    steps:
    -
      name: Checkout
      uses: actions/checkout@v2
    -
      name: Unshallow
      run: git fetch --prune --unshallow
    -
      name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.14
    -
       name: Run Builds
       run: |
         rm -rf ./out
         ./build.sh windows server
         ./build.sh windows desktop
    - name: Upload Build Artifact
      uses: actions/upload-artifact@v2
      with:
        # Artifact name
        # name: # optional
        path: ./out/**/*

  generate-release:
    name: Execute Release
    runs-on: ubuntu-latest
    needs: [build-linux, build-darwin, build-windows]
    steps:
    -
       name: Prepare Release Directory
       run: mkdir ./release
    - 
      name: Download a Build Artifact
      uses: actions/download-artifact@v2
      with:
        # Destination path
        path: ./release # optional
    - name: Display structure of downloaded files
      run: ls -R
      working-directory: ./release
